'''

# TO CREATE THE DATABASE
CREATE DATABASE COLLEGE;
# USE THIS COMMAND INSTEAD => CREATE DATABASE IF NOT EXISTS COLLEGE;


# TO CREATE THE TABLE
CREATE TABLE STUDENT;
# USE THIS COMMAND INSTEAD => CREATE TABLE IF NOT EXISTS STUDENT;


# TO DELETE THE TABLE 
DROP TABLE COLLEGE;
DROP TABLE IF EXIST COLLEGE;


# TO SEE THE TABLES
USE TABLE_NAME;
SHOW DATABASES;
SHOW TABLES;
'''